### ISSUE TITLE
help！！！！！！catkin_make错误

### ISSUE THREAD

**Issue by mco0308** [gjt15083576031/UR5_gripper_camera_gazebo#1]
![image](https://github.com/user-attachments/assets/8817c989-6ab9-4387-bff1-e010282b97be)

**Comment by Geo-JTao** [comment]
It may be that some libraries need to be installed through 'sudo apt-get install xxxx'.
I plan to provide ' install_ros_packages.sh ' in the new repository soon to help make it easier to run.
